#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr & 
feh --bg-scale ~/.wallpaper &
polybar &
xmodmap ~/.Xmodmap 


bspc monitor -d I II III IV V VI

# Borders and gaps
bspc config border_width    1
bspc config window_gap      7
# bspc config border_radius   12
# Borders colors
bspc config normal_border_color  "#b4befe"
bspc config focused_border_color  "#f38ba8"

bspc config focus_follows_pointer  true
bspc config history_awaretfocus  true
bspc config focus_by_distance  true


# Misc
bspc config split_ratio  0.52
bspc config borderless_monocle  true
bspc config gapless_monocle  true


